name: print-name
on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/print-name.yaml
jobs:
  printing:
    runs-on: ubuntu-latest
    steps:
      - name: print-name
        run: echo "Added print-name"

                
